# RDS Integration Example Configuration for AWS Lightsail
# This file demonstrates how to configure external RDS database integration

# AWS Configuration
aws:
  region: us-east-1
  
# Lightsail Instance Configuration
lightsail:
  instance_name: rds-demo-app
  static_ip: 98.91.3.69
  
# Application Configuration
application:
  name: rds-demo-app
  version: "1.0.0"
  type: web
  
  # Files to include in deployment package
  package_files:
    - "index.php"
    - "css/"
    - "config/"
  
  # Fallback: include all files if specific files don't exist
  package_fallback: true
  
  # Environment variables to set on the instance
  environment_variables:
    APP_ENV: production
    APP_DEBUG: false
    APP_NAME: "RDS Demo Application"

# Dependencies Configuration - External RDS Database Example
dependencies:
  # Web Server Dependencies
  apache:
    enabled: true
    version: "latest"
    config:
      document_root: "/var/www/html"
      enable_ssl: false
      enable_rewrite: true
  
  # External MySQL RDS Database Configuration
  mysql:
    enabled: true
    external: true  # This enables RDS integration instead of local installation
    rds:
      # RDS Database Configuration
      database_name: "my-rds-database"  # Name of your Lightsail RDS instance
      region: "us-east-1"               # AWS region where RDS is located
      
      # AWS Credentials for RDS API access
      # These should be set as GitHub Secrets for security
      access_key: "${AWS_ACCESS_KEY_ID}"     # GitHub Secret
      secret_key: "${AWS_SECRET_ACCESS_KEY}" # GitHub Secret
      
      # Optional: Custom environment variables for the application
      environment:
        DB_CONNECTION_TIMEOUT: "30"
        DB_CHARSET: "utf8mb4"
        DB_COLLATION: "utf8mb4_unicode_ci"
  
  # Alternative: External PostgreSQL RDS Database Configuration
  postgresql:
    enabled: false
    external: true  # This enables RDS integration instead of local installation
    rds:
      # RDS Database Configuration
      database_name: "my-postgres-rds"     # Name of your Lightsail RDS instance
      region: "us-east-1"                  # AWS region where RDS is located
      
      # AWS Credentials for RDS API access
      access_key: "${AWS_ACCESS_KEY_ID}"     # GitHub Secret
      secret_key: "${AWS_SECRET_ACCESS_KEY}" # GitHub Secret
      
      # Optional: Custom environment variables for the application
      environment:
        DB_CONNECTION_TIMEOUT: "30"
        DB_SSLMODE: "require"
  
  # Programming Language Dependencies
  php:
    enabled: true
    version: "8.1"
    config:
      extensions:
        - "pdo"
        - "pdo_mysql"
        - "curl"
        - "json"
        - "mbstring"
      enable_composer: true
  
  # Additional Dependencies
  git:
    enabled: true
    config:
      install_lfs: false
  
  # System Dependencies
  firewall:
    enabled: true
    config:
      allowed_ports:
        - "22"    # SSH
        - "80"    # HTTP
        - "443"   # HTTPS
      deny_all_other: true

# Deployment Configuration
deployment:
  # Timeout settings (in seconds)
  timeouts:
    ssh_connection: 120
    command_execution: 300
    health_check: 180
  
  # Retry settings
  retries:
    max_attempts: 3
    ssh_connection: 5
  
  # Deployment steps configuration
  steps:
    pre_deployment:
      common:
        enabled: true
        update_packages: true
        create_directories: true
        backup_enabled: true
      dependencies:
        enabled: true
        install_system_deps: true
        configure_services: true
    
    post_deployment:
      common:
        enabled: true
        verify_extraction: true
        create_env_file: true
        cleanup_temp_files: true
      dependencies:
        enabled: true
        configure_application: true
        set_permissions: true
        restart_services: true
        optimize_performance: true
    
    verification:
      enabled: true
      health_check: true
      external_connectivity: true
      performance_test: true
      security_check: true
      endpoints_to_test:
        - "/"

# GitHub Actions Configuration
github_actions:
  # Trigger configuration
  triggers:
    push_branches:
      - main
      - master
    pull_request_branches:
      - main
      - master
    workflow_dispatch: true
  
  # Job configuration
  jobs:
    test:
      enabled: true
      language_specific_tests: true
      local_server_test: true
      test_port: 8000
    
    deployment:
      # Only deploy on main branch
      deploy_on_push: true
      deploy_on_pr: false
      
      # Artifact retention
      artifact_retention_days: 1
      
      # Deployment summary
      create_summary: true

# Monitoring and Logging
monitoring:
  # Health check configuration
  health_check:
    endpoint: "/"
    expected_content: "Hello"
    max_attempts: 10
    wait_between_attempts: 10
    initial_wait: 30
  
  # Performance monitoring
  performance:
    response_time_check: true
    http_headers_check: true
  
  # Logging configuration
  logging:
    level: INFO
    include_timestamps: true
    include_deployment_metadata: true

# Security Configuration
security:
  # File permissions
  file_permissions:
    web_files: "644"
    directories: "755"
    config_files: "600"
  
  # Web server security
  web_server:
    hide_version: true
    disable_server_tokens: true
    enable_security_headers: true

# Backup Configuration
backup:
  enabled: true
  retention_days: 7
  backup_location: "/var/backups/deployments"
  include_database: false  # RDS handles its own backups
