#!/bin/bash

################################################################################
# Module: 04-github.sh
# Purpose: GitHub repository and workflow management
# Dependencies: 00-variables.sh, 01-utils.sh
#
# This module provides functions for:
# - Creating GitHub repositories
# - Setting up workflow directories
# - Creating .gitignore files
# - Committing and pushing changes to GitHub
################################################################################

# Function to create GitHub repository if needed
create_github_repo_if_needed() {
    local repo_name="$1"
    local repo_desc="$2"
    local visibility="$3"
    
    echo -e "${BLUE}Creating GitHub repository: $repo_name${NC}"
    
    if gh repo create "$repo_name" --description "$repo_desc" $visibility --confirm; then
        echo -e "${GREEN}✓ Repository created successfully${NC}"
        return 0
    else
        echo -e "${YELLOW}⚠️  Repository might already exist${NC}"
        return 0
    fi
}

# Function to setup workflow files
# NOTE: We no longer copy workflow files to new repos. Instead, the app-specific
# workflow calls the reusable workflow from the source repo directly. This ensures
# new repos always use the latest workflow code without needing manual updates.
setup_workflow_files() {
    echo -e "${BLUE}Setting up workflow directory...${NC}"
    
    mkdir -p .github/workflows
    
    echo -e "${GREEN}✓ Workflow directory created${NC}"
    echo -e "${BLUE}ℹ️  Using cross-repo workflow from naveenraj44125-creator/lamp-stack-lightsail${NC}"
    echo -e "${BLUE}ℹ️  No local workflow files needed - always uses latest from source repo${NC}"
    return 0
}

# Function to create .gitignore file
create_gitignore() {
    echo -e "${BLUE}Creating .gitignore file...${NC}"
    
    cat > ".gitignore" << 'GITIGNORE_EOF'
# Dependencies
node_modules/
npm-debug.log*
yarn-debug.log*
yarn-error.log*

# Runtime data
pids
*.pid
*.seed
*.pid.lock

# Coverage directory used by tools like istanbul
coverage/
*.lcov

# nyc test coverage
.nyc_output

# Logs
logs
*.log

# Runtime data
pids
*.pid
*.seed
*.pid.lock

# Directory for instrumented libs generated by jscoverage/JSCover
lib-cov

# Coverage directory used by tools like istanbul
coverage

# Grunt intermediate storage (https://gruntjs.com/creating-plugins#storing-task-files)
.grunt

# Bower dependency directory (https://bower.io/)
bower_components

# node-waf configuration
.lock-wscript

# Compiled binary addons (https://nodejs.org/api/addons.html)
build/Release

# Dependency directories
node_modules/
jspm_packages/

# TypeScript v1 declaration files
typings/

# Optional npm cache directory
.npm

# Optional eslint cache
.eslintcache

# Microbundle cache
.rpt2_cache/
.rts2_cache_cjs/
.rts2_cache_es/
.rts2_cache_umd/

# Optional REPL history
.node_repl_history

# Output of 'npm pack'
*.tgz

# Yarn Integrity file
.yarn-integrity

# dotenv environment variable files
.env
.env.development.local
.env.test.local
.env.production.local
.env.local

# parcel-bundler cache (https://parceljs.org/)
.cache
.parcel-cache

# Next.js build output
.next
out

# Nuxt.js build / generate output
.nuxt
dist

# Gatsby files
.cache/

# vuepress build output
.vuepress/dist

# Serverless directories
.serverless/

# FuseBox cache
.fusebox/

# DynamoDB Local files
.dynamodb/

# TernJS port file
.tern-port

# Stores VSCode versions used for testing VSCode extensions
.vscode-test

# yarn v2
.yarn/cache
.yarn/unplugged
.yarn/build-state.yml
.yarn/install-state.gz
.pnp.*

# AWS credentials and sensitive files
.aws-creds.sh
*.pem
*.key
trust-policy.json

# OS generated files
.DS_Store
.DS_Store?
._*
.Spotlight-V100
.Trashes
ehthumbs.db
Thumbs.db

# IDE files
.vscode/
.idea/
*.swp
*.swo
*~

# Temporary files
tmp/
temp/
GITIGNORE_EOF

    # Remove node_modules from git tracking if it was previously added
    # This prevents Code Defender from scanning AWS SDK example files
    if [ -d "node_modules" ]; then
        git rm -r --cached node_modules/ 2>/dev/null || true
    fi

    echo -e "${GREEN}✓ Created .gitignore${NC}"
}

# Function to commit and push changes
commit_and_push() {
    local app_type="$1"
    local app_name="$2"
    
    echo -e "${BLUE}Committing and pushing changes...${NC}"
    
    # Add all files
    git add .
    
    # Commit changes
    git commit -m "Add ${app_name} deployment configuration

- Added deployment-${app_type}.config.yml
- Added .github/workflows/deploy-${app_type}.yml  
- Added ${app_type} application files in root directory
- Configured for AWS Lightsail deployment via GitHub Actions

Generated by setup-complete-deployment.sh"
    
    # Push to GitHub
    if git push origin main; then
        echo -e "${GREEN}✓ Changes pushed to GitHub${NC}"
        return 0
    elif git push origin master; then
        echo -e "${GREEN}✓ Changes pushed to GitHub${NC}"
        return 0
    else
        echo -e "${RED}❌ Failed to push changes${NC}"
        return 1
    fi
}
